### PR TITLE
Feature: Husky pre-commit hook

### PR DESCRIPTION
**Pull request by OlegStotsky**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

This Pull Request adds husky pre-commit hook that runs prettier, tslint and then build script. If any of those return anything other than 0, the commit fails. That would help in enforcing consistent style between contributors, as well as enhancing stability of a project.

### CODE REVIEW

**Comment by JasonShin** [comment]
The pre-commit hook successfully runs `yarn lint` but it doesn't actually stop the committing. Is this intended? I think it should prevent you from making the commit, right?

**Comment by OlegStotsky** [comment]
If the lint command returns 0, then the commit shouldn't be stopped. Or am i missing something?

**Comment by OlegStotsky** [comment]
@JasonShin  That happens because "lint" script has --force flag, which makes tslint return 0 even if there are errors present. Should I remove it?

**Comment by JasonShin** [comment]
I've just pushed some updates
1. `.travis.yml` now uses `yarn lint` instead of `yarn test:lint`
2. `yarn test` now uses `yarn lint` instead of `yarn test:lint`

Testings
1. Manually ran `yarn test` locally and it was fine

**Comment by JasonShin** [comment]
Sorry, few more things to update ;) ...

1. Could you please create a branch again, but branch off `develop` instead of `master` and migrate the code over? Otherwise commits will look nasty ;( 



I checked after resolving the package.json merge conflict... and it like above image..

1. `.travis.yml` should use yarn lint instead of `yarn test:lint`
2. `yarn test` should use `yarn lint` instead of `yarn test:lint`

**Comment by JasonShin** [comment]
Travis is failing at

```
npx tslint -t verbose 'test/**/*.ts' 'src/**/*.ts' 'docs/**/*.ts'
ERROR: (ordered-imports) test/preprocessing/data.test.ts[8, 3]: Named imports must be alphabetized.
```

I'm not 100% sure why this is happening, it could be the side effect of removing `--force`. 

To resolve this issue, all you need to do is run

`yarn fix` ;)

**Comment by JasonShin** [comment]
The cause of the documentation error already exists in the `develop` branch. I propose we just fix it in this PR =) https://github.com/JasonShin/kalimdorjs/blob/develop/src/lib/utils/validation.ts#L12

**Comment by JasonShin** [comment]
Congratulations on the first contribution to Kalimdor!

**Pull request merged**
